refactor bot.py and utils.py
KostCode-Organization/hackathon_bot pull request #27
Opened 2024-11-22 00:20 UTC by godekina

@iamnovichek kindly review the changes made to telegram/bot.py and utils.py to refactor them.

2024-11-22 09:55 UTC, iamnovichek requested changes

2024-11-22 09:55 UTC, iamnovichek commented on tracker/telegram/bot.py
> +                Description: <blockquote>${description}</blockquote>
Please use `escaped_description`

2024-11-22 09:55 UTC, iamnovichek commented on tracker/telegram/bot.py
> +        message = message_template.safe_substitute(message_data)
We cannot access `message_data` here because it's a local variable

2024-11-22 09:55 UTC, iamnovichek commented on tracker/telegram/bot.py
> +        message = issue_message_template.safe_substitute(message_data)
The same. We cannot access `issue_message_template` and `message_data`

2024-11-22 09:55 UTC, iamnovichek commented on tracker/utils.py
> +            filter(
Please rollback the `filter` like it was before here - 
```
                filter(
                    lambda issue: issue.get("state") == "open"
                    and issue.get("assignee")
                    and not issue.get("draft")
                    and not issue.get("pull_request"),
                    issues,
                )
```

because it breaks the logic

2024-11-22 09:55 UTC, iamnovichek commented on tracker/utils.py
> +                and not issue.get("assignee")
Please replace 
```
and not issue.get("assignee")
and not issue.get("draft")
and not issue.get("pull_request"),
``` 
with `not any` statement

2024-11-22 21:27 UTC, godekina commented
@iamnovichek please is there way to contact you on Telegram? I have been getting a no 'db' error while trying to migrate the postgress db on the django app.

2024-11-22 23:14 UTC, iamnovichek commented
> @iamnovichek please is there way to contact you on Telegram? I have been getting a no 'db' error while trying to migrate the postgress db on the django app.

Sure. Here is my username - bobik300

2024-11-25 21:13 UTC, iamnovichek commented
@godekina Hi. How is it going?

2024-11-26 12:52 UTC, closed without merging