updated models/migrations
KostCode-Organization/hackathon_bot pull request #28
Opened 2024-11-22 21:08 UTC by binayak9932

ISSUE  #23 

- [X] Added time_limit field to Repository model
- [X] Updated migrations
- [X] Updated Repository model class docstring

2024-11-22 21:10 UTC, binayak9932 commented
@djeck1432  PTAL

2024-11-23 07:12 UTC, iamnovichek requested changes

2024-11-23 07:12 UTC, iamnovichek commented on tracker/models.py
> +    time_limit = models.PositiveIntegerField(default=86400)
Please, move this magic number to `traker/values.py` or `core/settings.py`

2024-11-23 14:53 UTC, binayak9932 commented
@iamnovichek  PTAL requested changes done

2024-11-23 14:56 UTC, iamnovichek approved these changes

2024-11-23 14:59 UTC, iamnovichek commented
@binayak9932 Could you please sync your code with the main branch?

2024-11-23 15:00 UTC, binayak9932 commented
> @binayak9932 Could you please sync your code with the main branch .

Done

2024-11-23 15:01 UTC, merged