Attach hyperlink to each issue
KostCode-Organization/hackathon_bot pull request #31
Opened 2024-11-23 22:24 UTC by codebestia

Fixes #24

2024-11-23 22:25 UTC, codebestia commented
@iamnovichek  Please review

2024-11-24 11:25 UTC, iamnovichek requested changes
Please, provide some screenshots to prove your changes work as expected

2024-11-24 11:25 UTC, iamnovichek commented on tracker/utils.py
> +def modify_issue_title(issue_title: str, issue_link: str) -> str:
Please, rename it to `attach_link_to_issue`

2024-11-25 05:49 UTC, codebestia commented
## The screenshots

![Screenshot from 2024-11-25 06-44-42](https://github.com/user-attachments/assets/5ff9c2c3-d13b-4b8c-a6b5-64f14b341749)
![Screenshot from 2024-11-25 06-44-53](https://github.com/user-attachments/assets/010d088c-4edb-4b94-89fa-c3f4b502bcfc)

2024-11-25 10:36 UTC, iamnovichek approved these changes

2024-11-25 10:37 UTC, iamnovichek commented
@codebestia approved

2024-11-25 10:38 UTC, merged