feat: Role choice when Signing Up
KostCode-Organization/hackathon_bot pull request #39
Opened 2024-11-27 16:16 UTC by Goodnessukaigwe

close #38

2024-11-27 16:33 UTC, iamnovichek requested changes

2024-11-27 16:33 UTC, iamnovichek commented on tracker/forms.py
> +from tracker.choices import Roles
Relative import works as well (`.choices`)

2024-11-27 16:33 UTC, iamnovichek commented on tracker/forms.py
> +    role = forms.ModelChoiceField(queryset=CustomUser.objects.all())
Please use `role = forms.ChoiceField(choices=Roles.choices)`

2024-11-27 16:33 UTC, iamnovichek commented on tracker/models.py
> +        max_length=11,
Please move this magic number to `values.py`

2024-11-27 16:33 UTC, iamnovichek commented on tracker/models.py
> +        choices=Roles,
Please use `Roles.choices`

2024-11-27 16:33 UTC, iamnovichek commented on tracker/templates/signup.html
> +                                    <option value="contributor">Contributor</option>
Use `for` loop. What if we will add move roles in the future?

2024-11-27 17:01 UTC, iamnovichek requested changes
Please provide some screenshots to prove your code works

2024-11-27 17:01 UTC, iamnovichek commented on tracker/values.py
> +ROLES_MAX_FIELD = 11
Bad constant name. Pls move it to dataclass as a class variable

2024-11-27 21:58 UTC, iamnovichek commented
@Goodnessukaigwe Pls sync with main

2024-11-27 22:06 UTC, iamnovichek requested changes
Pls provide also some screenshots to prove that it works

2024-11-27 22:06 UTC, iamnovichek commented on tracker/models.py
> +        user = self.create_user(email, password, role)
it won't work because `create_user` does not accept the third argument

2024-11-27 22:06 UTC, iamnovichek commented on tracker/models.py
> +ROLE_MAX_CHARACTER_LENGTH = 11
Pls move it to `values.py`

2024-11-28 16:53 UTC, iamnovichek requested changes
Pls provide some screenshots to prove that it works

2024-11-29 07:31 UTC, iamnovichek commented
@Goodnessukaigwe Pls resolve your merge conflicts

2024-11-29 07:34 UTC, djeck1432 requested changes

2024-11-29 07:34 UTC, djeck1432 commented on tracker/models.py
> +from .choices import Roles
don't use `relative import`

2024-11-29 11:14 UTC, merged