feat: Write tests for get_all_repostitories function
KostCode-Organization/hackathon_bot pull request #45
Opened 2024-11-29 21:54 UTC by No-bodyq

resolves #43 

![{C46ABC0D-7E4D-4343-8C0A-BD181066DD7C}](https://github.com/user-attachments/assets/3360fbf1-ebcf-466c-83f2-fabdb6687cfc)

2024-11-29 22:04 UTC, djeck1432 requested changes

2024-11-29 22:04 UTC, djeck1432 commented on tracker/tests/test_utils.py
> +os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings")
remove it, it's not needed, it should be in env variables

2024-11-29 22:04 UTC, djeck1432 commented on tracker/tests/test_utils.py
> +            email="testuser@example.com", role="CONTRIBUTOR"
use TextChoice from models.py class instead of str here

2024-11-29 22:04 UTC, djeck1432 commented on tracker/tests/test_utils.py
> +            email="testuser@example.com", role="CONTRIBUTOR"
please, use `Faker` to generate random email

2024-11-29 22:19 UTC, No-bodyq commented
All done @djeck1432

2024-11-30 07:50 UTC, iamnovichek requested changes

2024-11-30 07:50 UTC, iamnovichek commented on tracker/tests/test_utils.py
> +            telegram_id="123456789", user_id=self.custom_user.id
Pls fake the telegram ID too (it can be 9 or 10 digits integer if I'm right)

2024-11-30 07:50 UTC, iamnovichek commented on tracker/tests/test_utils.py
> +from faker import Faker
Pls update the dependencies file because we don't have `faker` in

2024-11-30 08:52 UTC, iamnovichek approved these changes

2024-11-30 08:53 UTC, merged