#22: Cover with tests CustomUser model
KostCode-Organization/hackathon_bot pull request #63
Opened 2024-12-28 07:00 UTC by aidenwong812

2024-12-28 11:08 UTC, iamnovichek requested changes

2024-12-28 11:08 UTC, iamnovichek commented on tracker/tests/test_models.py
> +        self.assertEqual(CustomUser.__str__(user), self.email)
pls use just `str(user)`

2024-12-28 11:08 UTC, iamnovichek commented on tracker/tests/test_models.py
> +        self.is_active = fake.boolean()
Pls set it to `True`

2024-12-28 11:08 UTC, iamnovichek commented on tracker/tests/test_models.py
> +        self.is_admin = fake.boolean()
Same

2024-12-28 11:08 UTC, iamnovichek commented on tracker/tests/test_models.py
> +        self.assertEqual(CustomUser.is_staff(user), self.is_admin)
pls use `user.is_staff`

2024-12-28 11:08 UTC, iamnovichek commented on tracker/tests/test_models.py
> +        self.assertEqual(CustomUser.is_project_lead(user), self.role == Roles.PROJECT_LEAD)
Same here

2024-12-29 19:34 UTC, iamnovichek requested changes

2024-12-29 19:34 UTC, iamnovichek commented on tracker/tests/test_models.py
> +        self.assertEqual(user.is_staff(), self.is_admin)
Use just `user.is_staff`

2024-12-29 19:34 UTC, iamnovichek commented on tracker/tests/test_models.py
> +        self.assertEqual(user.is_project_lead(), self.role == Roles.PROJECT_LEAD)
Same. You don't need to call a property

2024-12-30 10:21 UTC, iamnovichek approved these changes

2024-12-30 10:21 UTC, merged

2025-04-17 11:06 UTC, iamnovichek commented
@cryptogru812 tobi pyzda

2025-04-17 11:10 UTC, cryptogru812 commented
???